import random

def generate_specific_car(image_path, brand, model, year, description, color, fuel, gearBox, car_type, price, mileage, places, doors, category, location):
    car = {
        'brand': brand,
        'color': color,
        'year': year,
        'type': car_type,
        'power': random.randint(100, 500),
        'fuel': fuel,
        'gearBox': gearBox,
        'mileage': mileage,
        'model': model,
        'description': description,
        'price': price,
        'places': places,
        'doors': doors,
        'category': category,
        'pictures': [image_path],
        'location': location
    }
    return car

cars = [
    generate_specific_car(
        image_path="images/2008 2023.png",
        brand="Peugeot",
        model="2008",
        year=2023,
        description="Le Peugeot 2008 2023, un SUV compact au design moderne, parfait pour les citadins et les familles.",
        color="Gris métalisé",
        fuel="Essence",
        gearBox="Automatique",
        car_type="SUV",
        price=250.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="true"
    ),
    generate_specific_car(
        image_path="images/208 2023.png",
        brand="Peugeot",
        model="208",
        year=2023,
        description="La Peugeot 208 2023, une berline compacte avec un moteur essence, alliant confort et économie.",
        color="Rouge",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Berline",
        price=220.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="true"
    ),
    generate_specific_car(
        image_path="images/308 2023.png",
        brand="Peugeot",
        model="308",
        year=2023,
        description="La Peugeot 308 2023, une berline familiale offrant des performances hybrides et un intérieur raffiné.",
        color="Blanc",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Berline",
        price=280.00,
        mileage=5000,
        places=5,
        doors=5,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/5008 2023.png",
        brand="Peugeot",
        model="5008",
        year=2023,
        description="Le Peugeot 5008 2023, un SUV spacieux avec 7 places, idéal pour les familles nombreuses.",
        color="Gris métalisé",
        fuel="Diesel",
        gearBox="Automatique",
        car_type="SUV",
        price=35000.00,
        mileage=10000,
        places=7,
        doors=5,
        category="Familial",
        location="false"
    ),
    generate_specific_car(
        image_path="images/508 2023.png",
        brand="Peugeot",
        model="508",
        year=2023,
        description="La Peugeot 508 2023, une berline haut de gamme avec un design élégant et un moteur puissant.",
        color="Bleu",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Berline",
        price=400.00,
        mileage=5000,
        places=5,
        doors=4,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/A1 2023.png",
        brand="Audi",
        model="A1",
        year=2023,
        description="L'Audi A1 2023, une petite berline sportive avec un design moderne et une conduite agile.",
        color="Noir métalisé",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="Berline",
        price=25000.00,
        mileage=0,
        places=4,
        doors=3,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/A3 2023.png",
        brand="Audi",
        model="A3",
        year=2023,
        description="L'Audi A3 2023, une berline compacte avec des caractéristiques de luxe et un moteur hybride performant.",
        color="Gris",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Berline",
        price=300.00,
        mileage=5000,
        places=5,
        doors=4,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/A3 Berline 2023.png",
        brand="Audi",
        model="A3 Berline",
        year=2023,
        description="L'Audi A3 Berline 2023, une voiture de luxe offrant confort et performance avec une motorisation hybride.",
        color="Noir métalisé",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Berline",
        price=35000.00,
        mileage=3000,
        places=5,
        doors=4,
        category="Luxe",
        location="false"
    ),
    generate_specific_car(
        image_path="images/A4 2023.png",
        brand="Audi",
        model="A4",
        year=2023,
        description="L'Audi A4 2023, une berline intermédiaire offrant des caractéristiques de confort et de performance.",
        color="Bleu",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Berline",
        price=350.00,
        mileage=2000,
        places=5,
        doors=4,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/A45s AMG.png",
        brand="Mercedes",
        model="A45s AMG",
        year=2023,
        description="La Mercedes A45s AMG 2023, une voiture compacte sportive avec un moteur turbo haute performance.",
        color="Blanc",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Hatchback",
        price=60000.00,
        mileage=1000,
        places=5,
        doors=5,
        category="Sport",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Apocalypse supertruck.png",
        brand="Apocalypse",
        model="Supertruck",
        year=2023,
        description="L'Apocalypse Supertruck 2023, un véhicule tout-terrain extrême conçu pour les aventures les plus rudes.",
        color="Camouflage",
        fuel="Essence",
        gearBox="Automatique",
        car_type="4x4",
        price=700.00,
        mileage=5000,
        places=4,
        doors=4,
        category="Sport",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Aygo 2023.png",
        brand="Toyota",
        model="Aygo",
        year=2023,
        description="Le Toyota Aygo 2023, une petite citadine idéale pour les trajets urbains avec un moteur économique.",
        color="Rouge",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="Hatchback",
        price=18000.00,
        mileage=0,
        places=4,
        doors=3,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/C-HR 2024.png",
        brand="Toyota",
        model="C-HR",
        year=2024,
        description="Le Toyota C-HR 2024, un SUV hybride avec un design audacieux et une conduite confortable.",
        color="Gris métalisé",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="SUV",
        price=30000.00,
        mileage=1000,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Captur 2023.png",
        brand="Renault",
        model="Captur",
        year=2023,
        description="Le Renault Captur 2023, un SUV compact avec un design moderne et des technologies avancées.",
        color="Jaune",
        fuel="Essence",
        gearBox="Automatique",
        car_type="SUV",
        price=260.00,
        mileage=2000,
        places=5,
        doors=5,
        category="Économique",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Chiron W16 Mistral.png",
        brand="Bugatti",
        model="Chiron W16 Mistral",
        year=2023,
        description="Le Bugatti Chiron W16 Mistral 2023, un supercar ultra-luxueux avec une performance hors norme.",
        color="Bleu",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Sport",
        price=300000.00,
        mileage=1000,
        places=2,
        doors=2,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Clio 4 2023.png",
        brand="Renault",
        model="Clio 4",
        year=2023,
        description="La Renault Clio 4 2023, une petite berline dynamique avec un moteur essence fiable.",
        color="Rouge",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="Hatchback",
        price=22000.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Corolla 2024.png",
        brand="Toyota",
        model="Corolla",
        year=2024,
        description="La Toyota Corolla 2024, une berline fiable avec un moteur hybride, offrant confort et économie.",
        color="Blanc",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Berline",
        price=260.00,
        mileage=0,
        places=5,
        doors=4,
        category="Économique",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Dodge Challenger SRT.png",
        brand="Dodge",
        model="Challenger SRT",
        year=2023,
        description="Le Dodge Challenger SRT 2023, une voiture muscle avec un moteur V8 puissant et un design agressif.",
        color="Noir",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Coupé",
        price=550.00,
        mileage=5000,
        places=4,
        doors=2,
        category="Sport",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Ford RAM 2023.png",
        brand="Ford",
        model="RAM",
        year=2023,
        description="Le Ford RAM 2023, un pick-up robuste avec un moteur puissant, idéal pour les travaux lourds.",
        color="Gris",
        fuel="Diesel",
        gearBox="Automatique",
        car_type="Pick-up",
        price=40000.00,
        mileage=10000,
        places=5,
        doors=4,
        category="Sport",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Ford Ranger 2023.png",
        brand="Ford",
        model="Ranger",
        year=2023,
        description="Le Ford Ranger 2023, un pick-up polyvalent avec un moteur essence pour une conduite tout-terrain.",
        color="Bleu",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="Pick-up",
        price=350.00,
        mileage=5000,
        places=5,
        doors=4,
        category="Sport",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Golf 7 2024.png",
        brand="Volkswagen",
        model="Golf 7",
        year=2024,
        description="La Volkswagen Golf 7 2024, une berline compacte offrant une conduite dynamique avec un moteur hybride.",
        color="Noir",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Hatchback",
        price=27000.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/GT63s AMG.png",
        brand="Mercedes",
        model="GT63s AMG",
        year=2023,
        description="La Mercedes GT63s AMG 2023, une voiture de sport luxueuse avec un moteur V8 offrant une puissance exceptionnelle.",
        color="Gris",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Coupé",
        price=1200.00,
        mileage=2000,
        places=4,
        doors=4,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/ID 3 2024.png",
        brand="Volkswagen",
        model="ID 3",
        year=2024,
        description="La Volkswagen ID 3 2024, une voiture électrique compacte avec une autonomie impressionnante et un design futuriste.",
        color="Blanc",
        fuel="Électrique",
        gearBox="Automatique",
        car_type="Hatchback",
        price=30000.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Jeep Wrangler.png",
        brand="Jeep",
        model="Wrangler",
        year=2023,
        description="Le Jeep Wrangler 2023, un tout-terrain légendaire avec une capacité hors route impressionnante et un moteur puissant.",
        color="Vert",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="4x4",
        price=450.00,
        mileage=15000,
        places=4,
        doors=4,
        category="Sport",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Kangoo VP 2023.png",
        brand="Renault",
        model="Kangoo VP",
        year=2023,
        description="Le Renault Kangoo VP 2023, un utilitaire pratique avec un grand espace de chargement et un moteur diesel économique.",
        color="Blanc",
        fuel="Diesel",
        gearBox="Manuelle",
        car_type="Utilitaire",
        price=22000.00,
        mileage=5000,
        places=2,
        doors=4,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Maserati.png",
        brand="Maserati",
        model="Quattroporte",
        year=2023,
        description="La Maserati Quattroporte 2023, une berline de luxe avec un moteur V6 puissant et un design sophistiqué.",
        color="Gris",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Berline",
        price=800.00,
        mileage=3000,
        places=5,
        doors=4,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Maybach S680.png",
        brand="Maybach",
        model="S680",
        year=2023,
        description="Le Maybach S680 2023, une berline ultra-luxueuse avec des équipements haut de gamme et un confort inégalé.",
        color="Noir",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Berline",
        price=2000.00,
        mileage=2000,
        places=4,
        doors=4,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Megane 4 2023.png",
        brand="Renault",
        model="Megane 4",
        year=2023,
        description="La Renault Megane 4 2023, une berline compacte avec un design élégant et un moteur performant.",
        color="Bleu",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="Berline",
        price=24000.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Polo 6 2023.png",
        brand="Volkswagen",
        model="Polo 6",
        year=2023,
        description="La Volkswagen Polo 6 2023, une petite voiture urbaine avec un moteur essence et un intérieur moderne.",
        color="Rouge",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Hatchback",
        price=20000.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Prius 2024.png",
        brand="Toyota",
        model="Prius",
        year=2024,
        description="La Toyota Prius 2024, une voiture hybride emblématique avec une excellente économie de carburant et un design futuriste.",
        color="Gris",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Berline",
        price=280.00,
        mileage=0,
        places=5,
        doors=4,
        category="Économique",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Q2 2023.png",
        brand="Audi",
        model="Q2",
        year=2023,
        description="L'Audi Q2 2023, un SUV compact avec un design sportif et un moteur essence performant.",
        color="Blanc",
        fuel="Essence",
        gearBox="Automatique",
        car_type="SUV",
        price=30000.00,
        mileage=5000,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/RR Cullinan.png",
        brand="Rolls-Royce",
        model="Cullinan",
        year=2023,
        description="Le Rolls-Royce Cullinan 2023, un SUV de luxe avec une performance exceptionnelle et un confort inégalé.",
        color="Noir",
        fuel="Essence",
        gearBox="Automatique",
        car_type="SUV",
        price=3000.00,
        mileage=1000,
        places=5,
        doors=5,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/RR Spectre.png",
        brand="Rolls-Royce",
        model="Spectre",
        year=2023,
        description="Le Rolls-Royce Spectre 2023, un coupé de luxe électrique offrant une performance silencieuse et élégante.",
        color="Gris",
        fuel="Électrique",
        gearBox="Automatique",
        car_type="Coupé",
        price=350000.00,
        mileage=1000,
        places=4,
        doors=2,
        category="Luxe",
        location="false"
    ),
    generate_specific_car(
        image_path="images/RS3.png",
        brand="Audi",
        model="RS3",
        year=2023,
        description="L'Audi RS3 2023, une voiture sportive compacte avec un moteur turbo et une technologie avancée.",
        color="Rouge",
        fuel="Essence",
        gearBox="Automatique",
        car_type="Berline",
        price=600.00,
        mileage=1000,
        places=5,
        doors=4,
        category="Sport",
        location="true"
    ),
    generate_specific_car(
        image_path="images/T-ROC 2023.png",
        brand="Volkswagen",
        model="T-ROC",
        year=2023,
        description="Le Volkswagen T-ROC 2023, un SUV compact avec un design moderne et des caractéristiques haut de gamme.",
        color="Bleu",
        fuel="Essence",
        gearBox="Automatique",
        car_type="SUV",
        price=29000.00,
        mileage=3000,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Tiguan 2023.png",
        brand="Volkswagen",
        model="Tiguan",
        year=2023,
        description="Le Volkswagen Tiguan 2023, un SUV familial avec un moteur hybride et un intérieur spacieux.",
        color="Gris",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="SUV",
        price=320.00,
        mileage=10000,
        places=5,
        doors=5,
        category="Familial",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Toyota Land Cruiser.png",
        brand="Toyota",
        model="Land Cruiser",
        year=2023,
        description="Le Toyota Land Cruiser 2023, un SUV tout-terrain robuste avec des capacités exceptionnelles en hors-piste.",
        color="Noir",
        fuel="Diesel",
        gearBox="Automatique",
        car_type="SUV",
        price=50000.00,
        mileage=15000,
        places=5,
        doors=5,
        category="Sport",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Twingo 3 2022.png",
        brand="Renault",
        model="Twingo 3",
        year=2022,
        description="Le Renault Twingo 3 2022, une petite citadine avec un design unique et une conduite agile.",
        color="Jaune",
        fuel="Essence",
        gearBox="Manuelle",
        car_type="Hatchback",
        price=15000.00,
        mileage=0,
        places=4,
        doors=3,
        category="Économique",
        location="false"
    ),
    generate_specific_car(
        image_path="images/Urus.png",
        brand="Lamborghini",
        model="Urus",
        year=2023,
        description="Le Lamborghini Urus 2023, un SUV de luxe avec un moteur V8 performant et un design extravagant.",
        color="Gris",
        fuel="Essence",
        gearBox="Automatique",
        car_type="SUV",
        price=2500.00,
        mileage=2000,
        places=5,
        doors=5,
        category="Luxe",
        location="true"
    ),
    generate_specific_car(
        image_path="images/Yaris 2023.png",
        brand="Toyota",
        model="Yaris",
        year=2023,
        description="La Toyota Yaris 2023, une petite voiture économique avec un moteur hybride et un design compact.",
        color="Rouge",
        fuel="Hybride",
        gearBox="Automatique",
        car_type="Hatchback",
        price=20000.00,
        mileage=0,
        places=5,
        doors=5,
        category="Économique",
        location="false"
    )
]